// ============================================================
// Star Routes - Commodity Definitions (25 commodities)
// ============================================================

import { CommodityDef } from '../types';

export const COMMODITIES: CommodityDef[] = [
    // --- Raw Materials ---
    {
        id: 'iron_ore',
        name: 'Iron Ore',
        category: 'raw',
        basePrice: 20,
        volatility: 0.2,
        weight: 2,
        isContraband: false,
        description: 'Basic ore used in manufacturing. Abundant in mining systems.',
    },
    {
        id: 'rare_minerals',
        name: 'Rare Minerals',
        category: 'raw',
        basePrice: 80,
        volatility: 0.5,
        weight: 1,
        isContraband: false,
        description: 'Scarce minerals used in advanced tech. High value but volatile prices.',
    },
    {
        id: 'water',
        name: 'Water Ice',
        category: 'raw',
        basePrice: 10,
        volatility: 0.1,
        weight: 3,
        isContraband: false,
        description: 'Essential for life. Always in demand on frontier worlds.',
    },
    {
        id: 'helium3',
        name: 'Helium-3',
        category: 'raw',
        basePrice: 45,
        volatility: 0.3,
        weight: 1,
        isContraband: false,
        description: 'Fusion fuel isotope. Critical for starship reactors.',
    },
    // --- Industrial ---
    {
        id: 'fuel_cells',
        name: 'Fuel Cells',
        category: 'industrial',
        basePrice: 35,
        volatility: 0.3,
        weight: 2,
        isContraband: false,
        description: 'Refined fuel for ship engines. Every station needs them.',
    },
    {
        id: 'ship_parts',
        name: 'Ship Parts',
        category: 'industrial',
        basePrice: 60,
        volatility: 0.25,
        weight: 3,
        isContraband: false,
        description: 'Manufactured components for ship repair and upgrades.',
    },
    {
        id: 'polymers',
        name: 'Polymers',
        category: 'industrial',
        basePrice: 30,
        volatility: 0.2,
        weight: 2,
        isContraband: false,
        description: 'Synthetic materials for construction. Produced in refinery systems.',
    },
    {
        id: 'electronics',
        name: 'Electronics',
        category: 'industrial',
        basePrice: 55,
        volatility: 0.35,
        weight: 1,
        isContraband: false,
        description: 'Circuit boards and components. In demand everywhere.',
    },
    // --- Consumer ---
    {
        id: 'food',
        name: 'Food Supplies',
        category: 'consumer',
        basePrice: 15,
        volatility: 0.15,
        weight: 2,
        isContraband: false,
        description: 'Basic sustenance. Cheap to buy from agriculture worlds.',
    },
    {
        id: 'textiles',
        name: 'Textiles',
        category: 'consumer',
        basePrice: 25,
        volatility: 0.2,
        weight: 1,
        isContraband: false,
        description: 'Fabrics and clothing. Moderate value, stable market.',
    },
    {
        id: 'beverages',
        name: 'Fine Beverages',
        category: 'consumer',
        basePrice: 40,
        volatility: 0.3,
        weight: 2,
        isContraband: false,
        description: 'Wines, spirits, and exotic drinks. Popular in wealthy systems.',
    },
    // --- Tech ---
    {
        id: 'ai_cores',
        name: 'AI Cores',
        category: 'tech',
        basePrice: 150,
        volatility: 0.6,
        weight: 1,
        isContraband: false,
        description: 'Advanced artificial intelligence modules. Extremely valuable.',
    },
    {
        id: 'nanotech',
        name: 'Nanotech',
        category: 'tech',
        basePrice: 120,
        volatility: 0.5,
        weight: 1,
        isContraband: false,
        description: 'Microscopic machines for manufacturing and medicine.',
    },
    {
        id: 'quantum_chips',
        name: 'Quantum Chips',
        category: 'tech',
        basePrice: 200,
        volatility: 0.7,
        weight: 1,
        isContraband: false,
        factionExclusive: 'federation',
        description: 'Federation-exclusive quantum computing hardware.',
    },
    // --- Medical ---
    {
        id: 'medicine',
        name: 'Medicine',
        category: 'medical',
        basePrice: 50,
        volatility: 0.3,
        weight: 1,
        isContraband: false,
        description: 'Standard medical supplies. High demand in frontier and war zones.',
    },
    {
        id: 'biocultures',
        name: 'Biocultures',
        category: 'medical',
        basePrice: 90,
        volatility: 0.4,
        weight: 1,
        isContraband: false,
        description: 'Living biological samples for research and treatment.',
    },
    // --- Luxury ---
    {
        id: 'gemstones',
        name: 'Gemstones',
        category: 'luxury',
        basePrice: 180,
        volatility: 0.6,
        weight: 1,
        isContraband: false,
        description: 'Precious stones. Wealthy systems pay premium prices.',
    },
    {
        id: 'artifacts',
        name: 'Ancient Artifacts',
        category: 'luxury',
        basePrice: 250,
        volatility: 0.8,
        weight: 1,
        isContraband: false,
        description: 'Relics from dead civilizations. Wildly fluctuating value.',
    },
    {
        id: 'synth_silk',
        name: 'Synth Silk',
        category: 'luxury',
        basePrice: 100,
        volatility: 0.4,
        weight: 1,
        isContraband: false,
        factionExclusive: 'syndicate',
        description: 'Syndicate-produced luxury fabric. Sought after galaxy-wide.',
    },
    // --- Military ---
    {
        id: 'weapons',
        name: 'Weapons',
        category: 'military',
        basePrice: 70,
        volatility: 0.4,
        weight: 2,
        isContraband: false,
        description: 'Standard armaments. Legal but regulated in some systems.',
    },
    {
        id: 'military_tech',
        name: 'Military Tech',
        category: 'military',
        basePrice: 130,
        volatility: 0.5,
        weight: 2,
        isContraband: false,
        factionExclusive: 'hegemony',
        description: 'Hegemony-grade military hardware. Restricted outside their space.',
    },
    {
        id: 'shield_cores',
        name: 'Shield Cores',
        category: 'military',
        basePrice: 95,
        volatility: 0.35,
        weight: 1,
        isContraband: false,
        description: 'Energy cores for defensive shields. Essential for dangerous routes.',
    },
    // --- Contraband ---
    {
        id: 'narcotics',
        name: 'Narcotics',
        category: 'contraband',
        basePrice: 160,
        volatility: 0.7,
        weight: 1,
        isContraband: true,
        description: 'Illegal substances. Massive profit but huge risk if caught.',
    },
    {
        id: 'stolen_data',
        name: 'Stolen Data',
        category: 'contraband',
        basePrice: 200,
        volatility: 0.8,
        weight: 1,
        isContraband: true,
        description: 'Encrypted intelligence. Worth a fortune to the right buyer.',
    },
    {
        id: 'black_market_tech',
        name: 'Black Market Tech',
        category: 'contraband',
        basePrice: 300,
        volatility: 0.9,
        weight: 1,
        isContraband: true,
        description: 'Banned technology. The most profitable and dangerous cargo.',
    },
];

export const COMMODITY_MAP = new Map(COMMODITIES.map(c => [c.id, c]));

// Supply chain relationships: commodity -> what it needs to be produced
export const SUPPLY_CHAINS: Record<string, string[]> = {
    fuel_cells: ['helium3'],
    ship_parts: ['iron_ore', 'polymers'],
    electronics: ['rare_minerals', 'polymers'],
    polymers: ['iron_ore'],
    ai_cores: ['quantum_chips', 'electronics'],
    nanotech: ['rare_minerals', 'electronics'],
    medicine: ['biocultures', 'nanotech'],
    weapons: ['iron_ore', 'electronics'],
    military_tech: ['weapons', 'ai_cores'],
    shield_cores: ['rare_minerals', 'electronics'],
    black_market_tech: ['ai_cores', 'stolen_data'],
};

// What industries produce what
export const INDUSTRY_PRODUCTION: Record<string, string[]> = {
    mining: ['iron_ore', 'rare_minerals', 'water', 'helium3'],
    agriculture: ['food', 'textiles', 'beverages', 'biocultures'],
    manufacturing: ['ship_parts', 'polymers', 'electronics', 'weapons'],
    tech: ['ai_cores', 'nanotech', 'quantum_chips', 'electronics'],
    military: ['weapons', 'military_tech', 'shield_cores'],
    trading_hub: [],  // doesn't produce, but has everything in small quantities
    refinery: ['fuel_cells', 'polymers', 'helium3'],
    medical: ['medicine', 'biocultures', 'nanotech'],
    luxury: ['gemstones', 'synth_silk', 'artifacts', 'beverages'],
    frontier: ['water', 'food'], // barely produces anything
};

// What industries consume what
export const INDUSTRY_CONSUMPTION: Record<string, string[]> = {
    mining: ['fuel_cells', 'food', 'ship_parts', 'medicine'],
    agriculture: ['water', 'fuel_cells', 'electronics'],
    manufacturing: ['iron_ore', 'rare_minerals', 'fuel_cells', 'food'],
    tech: ['rare_minerals', 'electronics', 'food', 'fuel_cells'],
    military: ['fuel_cells', 'food', 'iron_ore', 'electronics', 'ship_parts'],
    trading_hub: ['food', 'fuel_cells'],
    refinery: ['iron_ore', 'helium3', 'fuel_cells'],
    medical: ['food', 'water', 'rare_minerals', 'electronics'],
    luxury: ['food', 'textiles', 'rare_minerals'],
    frontier: ['fuel_cells', 'ship_parts', 'medicine', 'electronics', 'weapons'],
};
