// ============================================================
// Star Routes - Ship Module Definitions (24 modules)
// ============================================================

import { ModuleDef } from '../types';

export const MODULES: ModuleDef[] = [
    // --- Weapons ---
    {
        id: 'laser_mk1',
        name: 'Laser Mk.I',
        type: 'weapon',
        tier: 1,
        price: 2000,
        effect: { combatBonus: 8 },
        description: 'Basic laser weapon. Reliable but weak.',
    },
    {
        id: 'laser_mk2',
        name: 'Laser Mk.II',
        type: 'weapon',
        tier: 2,
        price: 5000,
        effect: { combatBonus: 15 },
        description: 'Upgraded laser. Packs a punch.',
    },
    {
        id: 'plasma_cannon',
        name: 'Plasma Cannon',
        type: 'weapon',
        tier: 3,
        price: 12000,
        effect: { combatBonus: 25 },
        description: 'Heavy plasma weapon. Devastating firepower.',
    },
    // --- Shields ---
    {
        id: 'shield_mk1',
        name: 'Shield Mk.I',
        type: 'shield',
        tier: 1,
        price: 1500,
        effect: { shieldBonus: 20 },
        description: 'Basic energy shield. Adds protection.',
    },
    {
        id: 'shield_mk2',
        name: 'Shield Mk.II',
        type: 'shield',
        tier: 2,
        price: 4000,
        effect: { shieldBonus: 40 },
        description: 'Advanced shield generator. Solid defense.',
    },
    {
        id: 'fortress_shield',
        name: 'Fortress Shield',
        type: 'shield',
        tier: 3,
        price: 10000,
        effect: { shieldBonus: 70 },
        description: 'Military-grade shielding. Near impenetrable.',
    },
    // --- Engines ---
    {
        id: 'thruster_mk1',
        name: 'Thruster Mk.I',
        type: 'engine',
        tier: 1,
        price: 1800,
        effect: { speedBonus: 3 },
        description: 'Auxiliary thrusters. Modest speed improvement.',
    },
    {
        id: 'thruster_mk2',
        name: 'Thruster Mk.II',
        type: 'engine',
        tier: 2,
        price: 4500,
        effect: { speedBonus: 6 },
        description: 'High-performance thrusters. Noticeably faster.',
    },
    {
        id: 'warp_drive',
        name: 'Warp Drive',
        type: 'engine',
        tier: 3,
        price: 11000,
        effect: { speedBonus: 10 },
        description: 'Experimental propulsion. Blazing fast.',
    },
    // --- Cargo ---
    {
        id: 'cargo_bay_mk1',
        name: 'Cargo Bay Mk.I',
        type: 'cargo',
        tier: 1,
        price: 1200,
        effect: { cargoBonus: 15 },
        description: 'Extra cargo space. More goods, more profit.',
    },
    {
        id: 'cargo_bay_mk2',
        name: 'Cargo Bay Mk.II',
        type: 'cargo',
        tier: 2,
        price: 3500,
        effect: { cargoBonus: 30 },
        description: 'Expanded cargo hold. Serious hauling capacity.',
    },
    {
        id: 'cargo_bay_mk3',
        name: 'Cargo Bay Mk.III',
        type: 'cargo',
        tier: 3,
        price: 8000,
        effect: { cargoBonus: 50 },
        description: 'Massive cargo expansion. Turn any ship into a hauler.',
    },
    // --- Scanner ---
    {
        id: 'scanner_mk1',
        name: 'Scanner Mk.I',
        type: 'scanner',
        tier: 1,
        price: 1000,
        effect: { scanRange: 1 },
        description: 'Shows market prices of adjacent systems.',
    },
    {
        id: 'scanner_mk2',
        name: 'Scanner Mk.II',
        type: 'scanner',
        tier: 2,
        price: 3000,
        effect: { scanRange: 2 },
        description: 'Shows market prices of systems 2 jumps away.',
    },
    // --- Armor ---
    {
        id: 'armor_mk1',
        name: 'Hull Plating Mk.I',
        type: 'armor',
        tier: 1,
        price: 1500,
        effect: { hullBonus: 20 },
        description: 'Reinforced hull plating. Takes more hits.',
    },
    {
        id: 'armor_mk2',
        name: 'Hull Plating Mk.II',
        type: 'armor',
        tier: 2,
        price: 4000,
        effect: { hullBonus: 40 },
        description: 'Heavy hull reinforcement. Built like a tank.',
    },
    // --- Fuel Tank ---
    {
        id: 'fuel_tank_mk1',
        name: 'Fuel Tank Mk.I',
        type: 'fuel_tank',
        tier: 1,
        price: 800,
        effect: { fuelBonus: 30 },
        description: 'Additional fuel storage. Longer range.',
    },
    {
        id: 'fuel_tank_mk2',
        name: 'Fuel Tank Mk.II',
        type: 'fuel_tank',
        tier: 2,
        price: 2500,
        effect: { fuelBonus: 60 },
        description: 'Large auxiliary fuel tank. Go anywhere.',
    },
    // --- Repair ---
    {
        id: 'repair_bot',
        name: 'Repair Bot',
        type: 'repair',
        tier: 1,
        price: 2000,
        effect: { repairRate: 1 },
        description: 'Automated hull repair during travel.',
    },
    {
        id: 'repair_bay',
        name: 'Repair Bay',
        type: 'repair',
        tier: 2,
        price: 6000,
        effect: { repairRate: 3 },
        description: 'Full repair facility. Keeps your ship in shape.',
    },
    // --- Stealth ---
    {
        id: 'ecm_basic',
        name: 'ECM Suite',
        type: 'stealth',
        tier: 1,
        price: 2500,
        effect: { stealthBonus: 0.1, dangerReduction: 0.1 },
        description: 'Electronic countermeasures. Harder to detect.',
    },
    {
        id: 'cloak_device',
        name: 'Cloaking Device',
        type: 'stealth',
        tier: 3,
        price: 15000,
        effect: { stealthBonus: 0.3, dangerReduction: 0.25 },
        description: 'Experimental cloaking. Slip past enemies unseen.',
    },
    // --- Navigation ---
    {
        id: 'nav_computer',
        name: 'Nav Computer',
        type: 'navigation',
        tier: 1,
        price: 1500,
        effect: { dangerReduction: 0.05 },
        description: 'Better route calculation. Slightly safer travel.',
    },
    {
        id: 'astro_mapper',
        name: 'Astro Mapper',
        type: 'navigation',
        tier: 2,
        price: 5000,
        effect: { dangerReduction: 0.15 },
        description: 'Advanced stellar cartography. Much safer routes.',
    },
];

export const MODULE_MAP = new Map(MODULES.map(m => [m.id, m]));
