// ============================================================
// Star Routes - Ship Definitions (8 classes)
// ============================================================

import { ShipDef } from '../types';

export const SHIPS: ShipDef[] = [
    {
        id: 'swift_courier',
        name: 'Swift Courier',
        class: 'courier',
        baseCargoCapacity: 20,
        baseHull: 40,
        baseShield: 20,
        baseSpeed: 18,
        baseFuelCapacity: 80,
        moduleSlots: 2,
        price: 0,  // starter ship
        description: 'Small and fast. Perfect for urgent deliveries and learning the ropes.',
    },
    {
        id: 'pathfinder',
        name: 'Pathfinder',
        class: 'scout',
        baseCargoCapacity: 30,
        baseHull: 50,
        baseShield: 30,
        baseSpeed: 16,
        baseFuelCapacity: 120,
        moduleSlots: 3,
        price: 8000,
        description: 'Exploration vessel with long range. Good for charting new routes.',
    },
    {
        id: 'star_hauler',
        name: 'Star Hauler',
        class: 'light_freighter',
        baseCargoCapacity: 60,
        baseHull: 60,
        baseShield: 25,
        baseSpeed: 12,
        baseFuelCapacity: 100,
        moduleSlots: 3,
        price: 15000,
        description: 'A reliable light freighter. Good cargo space with decent speed.',
    },
    {
        id: 'bulk_carrier',
        name: 'Bulk Carrier',
        class: 'freighter',
        baseCargoCapacity: 100,
        baseHull: 80,
        baseShield: 20,
        baseSpeed: 8,
        baseFuelCapacity: 150,
        moduleSlots: 4,
        price: 30000,
        description: 'Massive cargo hold. Slow but profitable for high-volume runs.',
    },
    {
        id: 'titan_hauler',
        name: 'Titan Hauler',
        class: 'heavy_freighter',
        baseCargoCapacity: 160,
        baseHull: 120,
        baseShield: 30,
        baseSpeed: 6,
        baseFuelCapacity: 200,
        moduleSlots: 5,
        price: 55000,
        description: 'The biggest cargo vessel. A floating warehouse among the stars.',
    },
    {
        id: 'iron_merchant',
        name: 'Iron Merchant',
        class: 'armed_trader',
        baseCargoCapacity: 50,
        baseHull: 80,
        baseShield: 50,
        baseSpeed: 12,
        baseFuelCapacity: 110,
        moduleSlots: 4,
        price: 25000,
        description: 'Armed trading vessel. Balanced between cargo and combat capability.',
    },
    {
        id: 'viper',
        name: 'Viper',
        class: 'corvette',
        baseCargoCapacity: 25,
        baseHull: 100,
        baseShield: 70,
        baseSpeed: 16,
        baseFuelCapacity: 90,
        moduleSlots: 4,
        price: 40000,
        description: 'Fast combat vessel. Small cargo but excels in dangerous routes.',
    },
    {
        id: 'sovereign',
        name: 'Sovereign',
        class: 'galleon',
        baseCargoCapacity: 120,
        baseHull: 150,
        baseShield: 80,
        baseSpeed: 10,
        baseFuelCapacity: 180,
        moduleSlots: 6,
        price: 80000,
        description: 'The pinnacle of shipbuilding. Massive, tough, and versatile.',
    },
];

export const SHIP_MAP = new Map(SHIPS.map(s => [s.id, s]));
